// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2t_XkD8eC0yi_619kTeFHtW8z59riAE',
    appId: '1:465821748927:web:739388a6aa9b1cc7ecc00a',
    messagingSenderId: '465821748927',
    projectId: 'slowproject-e1c83',
    authDomain: 'slowproject-e1c83.firebaseapp.com',
    storageBucket: 'slowproject-e1c83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7e4g1j41-iINXQu5vXRZdkU04r2FGT-M',
    appId: '1:465821748927:android:321ef9767af270b7ecc00a',
    messagingSenderId: '465821748927',
    projectId: 'slowproject-e1c83',
    storageBucket: 'slowproject-e1c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCridz5KmGrdXbBnjRWaEt5-4cKE1ZzsZs',
    appId: '1:465821748927:ios:fbce816de27b536becc00a',
    messagingSenderId: '465821748927',
    projectId: 'slowproject-e1c83',
    storageBucket: 'slowproject-e1c83.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCridz5KmGrdXbBnjRWaEt5-4cKE1ZzsZs',
    appId: '1:465821748927:ios:fbce816de27b536becc00a',
    messagingSenderId: '465821748927',
    projectId: 'slowproject-e1c83',
    storageBucket: 'slowproject-e1c83.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi2t_XkD8eC0yi_619kTeFHtW8z59riAE',
    appId: '1:465821748927:web:6c0e41eb2bfbc5d2ecc00a',
    messagingSenderId: '465821748927',
    projectId: 'slowproject-e1c83',
    authDomain: 'slowproject-e1c83.firebaseapp.com',
    storageBucket: 'slowproject-e1c83.appspot.com',
  );
}
